name: postprocessing
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - anndata=0.10.8=pyhd8ed1ab_0
  - array-api-compat=1.7.1=pyhd8ed1ab_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.6.2=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2024.6.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.2.1=py312h8572e83_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - fonttools=4.53.0=py312h9a8786e_0
  - freetype=2.12.1=h267a509_2
  - get-annotations=0.1.2=pyhd8ed1ab_0
  - h5py=3.11.0=nompi_py312hb7ab980_102
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - icu=73.2=h59595ed_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py312h8572e83_1
  - krb5=1.21.2=h659d440_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - legacy-api-wrap=1.4=pyhd8ed1ab_1
  - lerc=4.0.0=h27087fc_0
  - libaec=1.1.3=h59595ed_0
  - libblas=3.9.0=22_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=22_linux64_openblas
  - libcurl=8.8.0=hca28451_0
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h77fa898_13
  - libgfortran-ng=13.2.0=h69a702a_13
  - libgfortran5=13.2.0=h3d2ce59_13
  - libgomp=13.2.0=h77fa898_13
  - libhwloc=2.10.0=default_h5622ce7_1001
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=22_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_h413a1c8_0
  - libpng=1.6.43=h2797004_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_13
  - libtiff=4.6.0=h1dd3fc0_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.16=hd590300_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=hc051c1a_1
  - libzlib=1.3.1=h4ab18f5_1
  - llvmlite=0.43.0=py312h9c5d478_0
  - matplotlib-base=3.8.4=py312h20ab3a6_2
  - munkres=1.1.4=pyh9f0ad1d_0
  - natsort=8.4.0=pyhd8ed1ab_0
  - ncurses=6.5=h59595ed_0
  - networkx=3.3=pyhd8ed1ab_1
  - numba=0.60.0=py312h83e6fd3_0
  - numpy=2.0.0=py312h22e1c76_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.1=h4ab18f5_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py312h1d6d2e6_1
  - patsy=0.5.6=pyhd8ed1ab_0
  - pillow=10.3.0=py312h287a98d_1
  - pip=24.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pynndescent=0.5.13=pyhff2d567_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - python=3.12.4=h194c7f8_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - readline=8.2=h8228510_1
  - scanpy=1.10.1=pyhd8ed1ab_0
  - scikit-learn=1.5.0=py312h1fcc3ea_1
  - scipy=1.13.1=py312hc2bc53b_0
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - session-info=1.0.0=pyhd8ed1ab_0
  - setuptools=70.1.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - statsmodels=0.14.2=py312h085067d_0
  - stdlib-list=0.10.0=pyhd8ed1ab_0
  - tbb=2021.12.0=h297d8ca_1
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - tqdm=4.66.4=pyhd8ed1ab_0
  - tzdata=2024a=h0c530f3_0
  - umap-learn=0.5.5=py312h7900ff3_1
  - wheel=0.43.0=pyhd8ed1ab_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - igraph==0.11.5
      - leidenalg==0.10.2
      - phenograph==1.5.7
      - psutil==6.0.0
      - texttable==1.7.0
